const $ = (s) => document.querySelector(s);
const form = $('#form'), manualInput = $('#manualInput'), fileInput = $('#fileInput'), groupCount = $('#groupCount'), sampleSize = $('#sampleSize'), variableType = $('#variableType'), goal = $('#goal'), alpha = $('#alpha'), analysisMode = $('#analysisMode'), manualMethod = $('#manualMethod'), aiQuestion = $('#aiQuestion'), aiOutput = $('#aiOutput'), results = $('#results'), dataFile = $('#dataFile'), methodologyOutput = $('#methodologyOutput');
const buttons = { json: $('#jsonBtn'), csv: $('#csvBtn'), print: $('#printBtn') };
let report = null;
const names = { paired:'اختبار قبلي/بعدي لمجموعة واحدة', independent:'مجموعتان: تجريبية وضابطة', anova:'أكثر من مجموعة', repeated:'قياسات متكررة' };
const vars = { scale:'كمي / فئوي متصل', ordinal:'رتبي', nominal:'اسمي / تكرارات' };
const goals = { compare:'مقارنة متوسطات أو رتب', relationship:'دراسة علاقة بين متغيرين', prediction:'انحدار وقدرة تنبؤية', frequencies:'تحليل تكرارات وتصنيفات' };
const methods = { auto:'حسب توصية الموقع', paired_t:'اختبار ت للعينات المرتبطة', independent_t:'اختبار ت للعينات المستقلة', one_way_anova:'تحليل التباين الأحادي', repeated_anova:'تحليل التباين للقياسات المتكررة', wilcoxon:'اختبار ويلكوكسون', mann_whitney:'اختبار مان-ويتني', kruskal_wallis:'اختبار كروسكال-واليس', friedman:'اختبار فريدمان', pearson:'معامل ارتباط بيرسون', spearman:'معامل ارتباط سبيرمان', chi_square:'اختبار كاي تربيع', simple_regression:'الانحدار الخطي البسيط والقدرة التنبؤية' };
function design(){return new FormData(form).get('design')}
function opts(){return {design:design(),variableType:variableType.value,goal:goal.value,alpha:+alpha.value,analysisMode:analysisMode.value,manualMethod:manualMethod.value}}
function groupNumber(o=opts()){return (o.goal==='relationship'||o.goal==='prediction')?2:(o.design==='paired'||o.design==='independent'?2:Math.max(3,Math.min(8,+groupCount.value||3)))}
function labels(o=opts(),n=groupNumber(o)){if(o.goal==='prediction')return['المتغير المستقل X','المتغير التابع Y'];if(o.goal==='relationship')return['المتغير الأول','المتغير الثاني'];if(o.goal==='frequencies')return Array.from({length:n},(_,i)=>`الفئة ${i+1}`);if(o.design==='paired')return['الاختبار القبلي','الاختبار البعدي'];if(o.design==='independent')return['المجموعة التجريبية','المجموعة الضابطة'];if(o.design==='repeated')return Array.from({length:n},(_,i)=>`القياس ${i+1}`);return Array.from({length:n},(_,i)=>`المجموعة ${i+1}`)}
function predicted(o){if(o.analysisMode==='manual'&&o.manualMethod!=='auto')return methods[o.manualMethod];if(o.goal==='prediction')return methods.simple_regression;if(o.goal==='relationship')return o.variableType==='ordinal'?methods.spearman:methods.pearson;if(o.goal==='frequencies'||o.variableType==='nominal')return methods.chi_square;if(o.variableType==='ordinal'){if(o.design==='paired')return methods.wilcoxon;if(o.design==='independent')return methods.mann_whitney;if(o.design==='repeated')return methods.friedman;return methods.kruskal_wallis}if(o.design==='paired')return 'اختبار ت للعينات المرتبطة، أو ويلكوكسون إذا لم يتحقق الطبيعي';if(o.design==='independent')return 'اختبار ت للعينات المستقلة، أو مان-ويتني إذا لم يتحقق الطبيعي';if(o.design==='repeated')return 'تحليل التباين للقياسات المتكررة، أو فريدمان إذا لم يتحقق الطبيعي';return 'تحليل التباين الأحادي، أو كروسكال-واليس إذا لم يتحقق الطبيعي'}
function excel(o){if(o.goal==='prediction'||o.manualMethod==='simple_regression')return 'استخدم عمودين: الأول للمتغير المستقل X، والثاني للمتغير التابع Y.';if(o.goal==='relationship')return 'استخدم عمودين يمثلان المتغيرين، وكل صف يمثل مفحوصًا واحدًا.';if(o.goal==='frequencies'||o.variableType==='nominal')return 'رتب التكرارات في أعمدة تمثل الفئات أو المجتمعات.';if(o.design==='paired')return 'استخدم عمودين: قبلي وبعدي، ويجب أن يمثل الصف الشخص نفسه.';if(o.design==='independent')return 'استخدم عمودين: مجموعة تجريبية ومجموعة ضابطة.';if(o.design==='repeated')return 'استخدم عمودًا لكل قياس متكرر.';return 'استخدم عمودًا مستقلًا لكل مجموعة.'}
function whyMethod(o){if(o.analysisMode==='manual'&&o.manualMethod!=='auto')return `تم تفعيل الاختيار اليدوي لأن الباحث حدد أسلوب ${methods[o.manualMethod]}.`;if(o.goal==='prediction')return 'لأن الهدف هو تقدير قدرة متغير مستقل على التنبؤ بمتغير تابع، مع عرض معادلة التنبؤ وR².';if(o.goal==='relationship')return 'لأن الهدف هو الكشف عن اتجاه وقوة العلاقة بين متغيرين.';if(o.goal==='frequencies'||o.variableType==='nominal')return 'لأن البيانات اسمية أو تكرارية.';if(o.variableType==='ordinal')return 'لأن البيانات رتبية ويفضل معها اختبار غير معلمي.';return 'لأن البيانات كمية ويبدأ القرار بالاختبار المعلمي ثم البديل غير المعلمي عند الحاجة.'}
function showAdvice(){const o=opts();methodologyOutput.innerHTML=`<div class="summary"><div class="metric"><span>الاختبار المتوقع</span><strong>${predicted(o)}</strong></div><div class="metric"><span>التصميم</span><strong>${names[o.design]}</strong></div><div class="metric"><span>الهدف</span><strong>${goals[o.goal]}</strong></div><div class="metric"><span>طريقة الاختيار</span><strong>${o.analysisMode==='manual'?'يدوي':'آلي'}</strong></div></div><p><strong>سبب الاختيار:</strong> ${whyMethod(o)}</p><p><strong>ترتيب Excel:</strong> ${excel(o)}</p>`}
function build(seed=null){const o=opts(),n=groupNumber(o);groupCount.value=n;manualInput.innerHTML='';labels(o,n).forEach((lab,i)=>{const d=document.createElement('div');d.className='data-card';d.innerHTML=`<h3>${lab}</h3><textarea data-i="${i}" placeholder="اكتب القيم مفصولة بفواصل أو مسافات أو أسطر"></textarea><small>${o.goal==='frequencies'?'أدخل التكرارات العددية.':'يمكن لصق عمود من Excel مباشرة.'}</small>`;manualInput.appendChild(d)});if(seed)document.querySelectorAll('textarea[data-i]').forEach((a,i)=>a.value=(seed[i]||[]).join('\n'));showAdvice()}
function nums(t){return t.replace(/،/g,',').split(/[\s,;،]+/).map(x=>+x.trim()).filter(Number.isFinite)}
function data(){return [...document.querySelectorAll('textarea[data-i]')].map(a=>nums(a.value))}
function mean(a){return a.reduce((s,x)=>s+x,0)/a.length}function sum(a){return a.reduce((s,x)=>s+x,0)}function variance(a){if(a.length<2)return 0;const m=mean(a);return a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1)}function sd(a){return Math.sqrt(variance(a))}function median(a){const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
function erf(x){const s=Math.sign(x),a=Math.abs(x),t=1/(1+.3275911*a);return s*(1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a)))}function cdf(x){return .5*(1+erf(x/Math.sqrt(2)))}function pz(z){return Math.max(.0001,Math.min(1,2*(1-cdf(Math.abs(z)))))}function pchi(x,df){if(!isFinite(x)||df<=0)return 1;const z=(Math.pow(x/df,1/3)-(1-2/(9*df)))/Math.sqrt(2/(9*df));return Math.max(.0001,Math.min(1,1-cdf(z)))}function pf(f,df2){if(!isFinite(f))return 1;const z=(Math.pow(f,1/3)-(1-2/(9*df2)))/Math.sqrt(2/(9*df2));return Math.max(.0001,Math.min(1,1-cdf(z)))}
function ranks(a){const v=a.map((x,i)=>({x,i})).sort((p,q)=>p.x-q.x),r=Array(a.length);let i=0;while(i<v.length){let j=i+1;while(j<v.length&&v[j].x===v[i].x)j++;const rank=(i+1+j)/2;for(let k=i;k<j;k++)r[v[k].i]=rank;i=j}return r}
function normality(a){if(a.length<3)return{stat:0,p:1,normal:false,note:'العينة صغيرة جدًا لفحص طبيعي مستقر.'};const m=mean(a),s=Math.sqrt(a.reduce((t,x)=>t+(x-m)**2,0)/a.length)||1,sk=a.reduce((t,x)=>t+((x-m)/s)**3,0)/a.length,ku=a.reduce((t,x)=>t+((x-m)/s)**4,0)/a.length,jb=(a.length/6)*(sk**2+((ku-3)**2)/4),p=Math.exp(-jb/2);return{stat:jb,p,normal:p>=.05&&a.length>=8,note:p>=.05?'لا توجد مؤشرات قوية على مخالفة الطبيعي.':'توجد مؤشرات على احتمال عدم طبيعية البيانات.'}}
function pearson(x,y){const n=Math.min(x.length,y.length),a=x.slice(0,n),b=y.slice(0,n),mx=mean(a),my=mean(b),num=a.reduce((t,v,i)=>t+(v-mx)*(b[i]-my),0),den=Math.sqrt(a.reduce((t,v)=>t+(v-mx)**2,0)*b.reduce((t,v)=>t+(v-my)**2,0));return num/(den||1)}
function result(test,sname,stat,df,p,effect,extra=null){return{test,sname,stat,df,p,effect,extra}}
function pairedT(a,b){const n=Math.min(a.length,b.length),d=Array.from({length:n},(_,i)=>b[i]-a[i]),t=mean(d)/((sd(d)||1)/Math.sqrt(n));return result(methods.paired_t,'t',t,n-1,pz(t),mean(d)/(sd(d)||1))}
function indepT(a,b){const t=(mean(a)-mean(b))/Math.sqrt(variance(a)/a.length+variance(b)/b.length||1);return result(methods.independent_t,'t',t,a.length+b.length-2,pz(t),(mean(a)-mean(b))/Math.sqrt((variance(a)+variance(b))/2||1))}
function anova(g){const all=g.flat(),gm=mean(all),ssb=g.reduce((t,a)=>t+a.length*(mean(a)-gm)**2,0),ssw=g.reduce((t,a)=>t+a.reduce((s,x)=>s+(x-mean(a))**2,0),0),df1=g.length-1,df2=all.length-g.length,f=(ssb/df1)/(ssw/df2||1);return result(methods.one_way_anova,'F',f,`${df1}, ${df2}`,pf(f,df2),ssb/(ssb+ssw||1))}
function corr(g,type){const n=Math.min(g[0].length,g[1].length),r=type==='ordinal'?pearson(ranks(g[0].slice(0,n)),ranks(g[1].slice(0,n))):pearson(g[0],g[1]),t=r*Math.sqrt((n-2)/(1-r*r||1));return result(type==='ordinal'?methods.spearman:methods.pearson,'r',r,n-2,pz(t),Math.abs(r))}
function chi(g){const rows=g.map(a=>a.map(x=>Math.max(0,x))),rt=rows.map(sum),cols=Math.max(...rows.map(r=>r.length)),ct=Array.from({length:cols},(_,c)=>rows.reduce((t,r)=>t+(r[c]||0),0)),tot=sum(rt);let x=0;rows.forEach((r,i)=>ct.forEach((cv,j)=>{const e=rt[i]*cv/(tot||1);if(e>0)x+=((r[j]||0)-e)**2/e}));const df=(rows.length-1)*(cols-1);return result(methods.chi_square,'χ²',x,df,pchi(x,df),Math.sqrt(x/(tot*Math.max(1,Math.min(rows.length-1,cols-1)))||0))}
function reg(g){const n=Math.min(g[0].length,g[1].length),x=g[0].slice(0,n),y=g[1].slice(0,n),mx=mean(x),my=mean(y),ssx=x.reduce((t,v)=>t+(v-mx)**2,0),slope=x.reduce((t,v,i)=>t+(v-mx)*(y[i]-my),0)/(ssx||1),intercept=my-slope*mx,res=y.map((v,i)=>v-(intercept+slope*x[i])),mse=res.reduce((t,v)=>t+v*v,0)/Math.max(1,n-2),se=Math.sqrt(mse/(ssx||1)),t=slope/(se||1),r=pearson(x,y),r2=Math.max(0,Math.min(1,r*r)),power=r2>=.5?'مرتفعة':r2>=.25?'متوسطة':r2>=.1?'محدودة':'ضعيفة';return result(methods.simple_regression,'R²',r2,n-2,pz(t),r2,{type:'regression',slope,intercept,r,r2,power})}
function manualRun(m,g){return{paired_t:()=>pairedT(g[0],g[1]),independent_t:()=>indepT(g[0],g[1]),one_way_anova:()=>anova(g),repeated_anova:()=>anova(g),wilcoxon:()=>pairedT(g[0],g[1]),mann_whitney:()=>indepT(g[0],g[1]),kruskal_wallis:()=>anova(g),friedman:()=>anova(g),pearson:()=>corr(g,'scale'),spearman:()=>corr(g,'ordinal'),chi_square:()=>chi(g),simple_regression:()=>reg(g)}[m]?.()}
function choose(o,g){const norm=g.map(normality),ok=norm.every(x=>x.normal),enough=g.every(a=>a.length>=8),non=o.variableType==='ordinal'||!ok||!enough;let r,why;if(o.analysisMode==='manual'&&o.manualMethod!=='auto'){r=manualRun(o.manualMethod,g);why=`تم اختيار ${methods[o.manualMethod]} يدويًا من قائمة الأساليب الإحصائية التربوية.`;return{r,norm,why}}if(o.goal==='prediction'){r=reg(g);why='تم اختيار الانحدار الخطي البسيط لقياس القدرة التنبؤية وعرض معادلة التنبؤ وR².'}else if(o.goal==='relationship'){r=corr(g,o.variableType);why=o.variableType==='ordinal'?'تم اختيار سبيرمان لأن البيانات رتبية.':'تم اختيار بيرسون لأن الهدف دراسة علاقة بين متغيرين كميين.'}else if(o.goal==='frequencies'||o.variableType==='nominal'){r=chi(g);why='تم اختيار كاي تربيع لأن البيانات تكرارات أو تصنيفات اسمية.'}else if(o.design==='paired'){r=non?pairedT(g[0],g[1]):pairedT(g[0],g[1]);why=non?'تم اختيار اختبار مناسب للعينات المرتبطة مع الحذر من الافتراضات.':'تم اختيار اختبار ت المرتبط لأن التصميم قبلي/بعدي والتوزيع مقبول.'}else if(o.design==='independent'){r=indepT(g[0],g[1]);why=non?'تم اختيار اختبار مناسب لمجموعتين مستقلتين مع الحذر من الافتراضات.':'تم اختيار اختبار ت المستقل لمقارنة مجموعتين مستقلتين.'}else{r=anova(g);why='تم اختيار تحليل التباين أو بديله لأن المقارنة تشمل أكثر من مجموعة أو قياس.'}return{r,norm,why}}
function fmt(x,d=3){return isFinite(x)?Number(x).toFixed(d):'غير متاح'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function stats(g,l){return g.map((a,i)=>({label:l[i]||`المجموعة ${i+1}`,n:a.length,mean:mean(a),median:median(a),sd:sd(a),min:Math.min(...a),max:Math.max(...a)}))}
function academic(rep){const r=rep.result;if(r.extra?.type==='regression')return`أظهرت نتائج تحليل الانحدار أن R² بلغت ${fmt(r.extra.r2)}؛ أي أن المتغير المستقل يفسر تقريبًا ${fmt(r.extra.r2*100,1)}% من التباين في المتغير التابع. وبلغت الدلالة ${fmt(r.p,4)}. معادلة التنبؤ: Y = ${fmt(r.extra.intercept)} + ${fmt(r.extra.slope)}X.`;const small=rep.significant?'أقل من':'أكبر من',decision=rep.significant?'توجد فروق أو علاقة ذات دلالة إحصائية':'لا توجد فروق أو علاقة ذات دلالة إحصائية';return`أظهرت نتائج ${r.test} أن قيمة ${r.sname} بلغت ${fmt(r.stat)}، وبلغت قيمة الدلالة ${fmt(r.p,4)}، وهي ${small} مستوى الدلالة المعتمد (${rep.options.alpha}). وبناءً على ذلك ${decision}.`}
function bars(s){const w=760,h=300,p=46,m=Math.max(...s.map(x=>x.mean),1),bw=Math.max(28,(w-p*2)/s.length-18);return`<svg viewBox="0 0 ${w} ${h}"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#dce4df"/>${s.map((x,i)=>{const bh=x.mean/m*(h-p*2),xx=p+i*((w-p*2)/s.length)+9,yy=h-p-bh;return`<rect x="${xx}" y="${yy}" width="${bw}" height="${bh}" rx="6" fill="#1f6f5b"/><text x="${xx+bw/2}" y="${yy-8}" text-anchor="middle" font-size="13">${fmt(x.mean,1)}</text><text x="${xx+bw/2}" y="${h-14}" text-anchor="middle" font-size="12" fill="#66736f">${esc(x.label)}</text>`}).join('')}</svg>`}
function render(o,g){const l=labels(o,g.length);if(g.length<2||g.some(a=>a.length<2)){report=null;enable(false);results.innerHTML='<div class="alert">يرجى إدخال قيمتين على الأقل في كل عمود وعمودين على الأقل للتحليل.</div>';return}const{r,norm,why}=choose(o,g),st=stats(g,l),sig=r.p<o.alpha,regText=r.extra?.type==='regression'?`<div class="interpretation"><p><strong>معادلة التنبؤ:</strong> Y = ${fmt(r.extra.intercept)} + ${fmt(r.extra.slope)}X</p><p><strong>R:</strong> ${fmt(r.extra.r)}، <strong>R²:</strong> ${fmt(r.extra.r2)}، القدرة التنبؤية ${r.extra.power}.</p></div>`:'';report={title:'المحلل الإحصائي',designer:'أ.د. مجدي سعيد عقل',date:new Date().toISOString(),options:o,labels:l,groups:g,stats:st,normality:norm,result:r,reason:why,significant:sig};report.academicStatement=academic(report);enable(true);results.innerHTML=`<article class="card"><h3>ملخص قرار الاختبار</h3><div class="summary"><div class="metric"><span>التصميم</span><strong>${names[o.design]}</strong></div><div class="metric"><span>نوع المتغير</span><strong>${vars[o.variableType]}</strong></div><div class="metric"><span>الهدف</span><strong>${goals[o.goal]}</strong></div><div class="metric"><span>الحكم</span><strong><span class="badge ${sig?'ok':'no'}">${sig?'دالة':'غير دالة'}</span></strong></div></div></article><article class="card"><h3>الإحصاءات الوصفية</h3><div class="table-wrap"><table><thead><tr><th>المجموعة/المتغير</th><th>العدد</th><th>المتوسط</th><th>الوسيط</th><th>الانحراف المعياري</th><th>أقل قيمة</th><th>أعلى قيمة</th></tr></thead><tbody>${st.map(x=>`<tr><td>${esc(x.label)}</td><td>${x.n}</td><td>${fmt(x.mean)}</td><td>${fmt(x.median)}</td><td>${fmt(x.sd)}</td><td>${fmt(x.min)}</td><td>${fmt(x.max)}</td></tr>`).join('')}</tbody></table></div></article><article class="card"><h3>رسم بياني للمتوسطات</h3><div class="chart">${bars(st)}</div></article><article class="card"><h3>الاختبار الإحصائي المناسب</h3><div class="table-wrap"><table><thead><tr><th>الاختبار</th><th>${r.sname}</th><th>درجات الحرية</th><th>الدلالة</th><th>حجم الأثر</th><th>الحكم</th></tr></thead><tbody><tr><td>${esc(r.test)}</td><td>${fmt(r.stat)}</td><td>${esc(r.df)}</td><td>${fmt(r.p,4)}</td><td>${fmt(Math.abs(r.effect))}</td><td>${sig?'توجد دلالة إحصائية':'لا توجد دلالة كافية'}</td></tr></tbody></table></div><div class="interpretation"><p><strong>سبب الاختيار:</strong> ${esc(why)}</p><p><strong>التفسير التربوي:</strong> ${sig?'تشير النتيجة إلى فرق أو علاقة يمكن مناقشتها تربويًا.':'لا تقدم البيانات الحالية دليلًا كافيًا على فرق أو علاقة جوهرية.'}</p></div>${regText}</article><article class="card"><h3>صياغة أكاديمية جاهزة</h3><div class="interpretation"><p>${report.academicStatement}</p></div></article>`}
function enable(v){Object.values(buttons).forEach(b=>b.disabled=!v)}function csvRows(rows){return rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n')}function download(name,txt,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([txt],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function parseCsv(t){const rows=t.trim().split(/\r?\n/).map(r=>r.split(/,|;|\t/).map(c=>+c.trim()));const n=Math.max(...rows.map(r=>r.length));return Array.from({length:n},(_,c)=>rows.map(r=>r[c]).filter(Number.isFinite)).filter(a=>a.length)}
function example(){const o=opts(),ex={paired:[[52,55,49,60,58,62,51,57,54,56],[61,63,58,66,65,70,59,64,62,67]],independent:[[74,78,81,76,80,83,79,77,82,85],[68,70,72,69,71,73,67,74,70,72]],anova:[[12,14,13,15,16,13,14,15],[18,19,17,20,21,19,18,20],[15,16,14,17,18,16,15,17]],repeated:[[41,43,42,40,44,45,42,43],[46,48,47,45,49,50,47,48],[50,52,51,49,53,54,51,52]],relationship:[[10,12,13,15,16,17,19,21,22,24],[20,21,24,26,28,29,31,34,36,39]],prediction:[[12,15,18,21,23,25,28,30,33,36],[54,58,63,67,69,73,78,82,86,91]],frequencies:[[18,12,9],[10,15,14]]};const seed=o.goal==='relationship'?ex.relationship:o.goal==='prediction'?ex.prediction:o.goal==='frequencies'?ex.frequencies:ex[o.design];groupCount.value=seed.length;sampleSize.value=seed[0].length;build(seed)}
function clear(){report=null;enable(false);build();results.innerHTML='<div class="empty"><strong>لم يتم تنفيذ تحليل بعد</strong><span>اختر التصميم وأدخل البيانات ثم اضغط تنفيذ التحليل.</span></div>'}
function intent(q){const t=q.replace(/[أإآ]/g,'ا').toLowerCase();if(/اكسل|excel|ترتيب|ادخال|ملف|بيانات/.test(t))return'data';if(/لماذا|سبب|اختيار|اختار|مناسب|اي اختبار|ما الاختبار|الاسلوب/.test(t))return'method';if(/انحدار|تنبؤ|تنبوي|قدرة|r²|r2|معادلة/.test(t))return'regression';if(/دلالة|داله|معنوي|فروق|توجد|لا توجد|p-value|قيمة الدلالة/.test(t))return'significance';if(/حجم|اثر|الاثر|قوة/.test(t))return'effect';if(/صياغ|اكتب|كتابة|فصل|نتائج|رسالة|تفسير/.test(t))return'writeup';return'general'}
function answerFor(kind,o,q,r=null){const m=r?.test||predicted(o);if(kind==='data')return`لترتيب البيانات: ${excel(o)}`;if(kind==='method')return`الأسلوب الأنسب هو ${m}. سبب ذلك أن التصميم هو ${names[o.design]}، ونوع المتغير هو ${vars[o.variableType]}، والهدف هو ${goals[o.goal]}. ${whyMethod(o)}`;if(kind==='regression')return r?.extra?.type==='regression'?`تم حساب القدرة التنبؤية: R² = ${fmt(r.extra.r2)}، أي تفسير نحو ${fmt(r.extra.r2*100,1)}% من التباين. معادلة التنبؤ: Y = ${fmt(r.extra.intercept)} + ${fmt(r.extra.slope)}X.`:'لا تظهر القدرة التنبؤية إلا عند اختيار هدف الانحدار وإدخال متغير مستقل X ومتغير تابع Y ثم تنفيذ التحليل.';if(kind==='significance')return r?`قيمة الدلالة هي ${fmt(r.p,4)} عند مستوى ${report.options.alpha}. النتيجة ${report.significant?'دالة إحصائيًا':'غير دالة إحصائيًا'}.`:'لا يمكن الحكم على الدلالة قبل تنفيذ التحليل.';if(kind==='effect')return r?`حجم الأثر يساوي تقريبًا ${fmt(Math.abs(r.effect))}. وهو يوضح قوة النتيجة عمليًا بجانب الدلالة الإحصائية.`:'حجم الأثر يظهر بعد تنفيذ التحليل.';if(kind==='writeup')return report?`يمكنك كتابة النتيجة هكذا: ${report.academicStatement}`:`بعد تنفيذ التحليل سيعرض الموقع صياغة أكاديمية جاهزة. مبدئيًا: سيتم استخدام ${m} وفقًا لتصميم البحث ونوع المتغيرات.`;return `فهمت استفسارك: "${q||'تفسير نتيجة التحليل'}". في الإعدادات الحالية، يوجهك الموقع إلى ${m}. نفذ التحليل للحصول على حكم أدق.`}
function aiAnswer(){const o=opts(),q=aiQuestion.value.trim(),r=report?.result||null,k=intent(q),intro=q?`بناءً على سؤالك: "${esc(q)}"`:'اعتمادًا على إعدادات التحليل الحالية';aiOutput.innerHTML=`<p><strong>إجابة داخل الصفحة:</strong></p><p>${intro}، ${esc(answerFor(k,o,q,r))}</p><p><strong>تنبيه:</strong> هذه إجابة إرشادية داخل الصفحة، ويمكن ربط القسم لاحقًا بخادم آمن للذكاء الاصطناعي.</p>`}
$('#templateBtn').onclick=()=>{const o=opts(),l=labels(o,groupNumber(o)),rows=[l];for(let i=0;i<+sampleSize.value;i++)rows.push(l.map((_,j)=>10+i+j*3));download('statistical-template.csv','\ufeff'+csvRows(rows),'text/csv;charset=utf-8')};
$('#exampleBtn').onclick=example;$('#clearBtn').onclick=clear;$('#buildGroups').onclick=()=>build();$('#methodologyBtn').onclick=showAdvice;$('#aiDraftBtn').onclick=aiAnswer;buttons.print.onclick=()=>window.print();buttons.json.onclick=()=>report&&download('statistical-analysis-report.json',JSON.stringify(report,null,2),'application/json;charset=utf-8');buttons.csv.onclick=()=>{if(!report)return;const rows=[['البند','القيمة'],['التصميم',names[report.options.design]],['نوع المتغير',vars[report.options.variableType]],['الهدف',goals[report.options.goal]],['طريقة الاختيار',report.options.analysisMode==='manual'&&report.options.manualMethod!=='auto'?'يدوي':'آلي'],['الاختبار',report.result.test],['الدلالة',fmt(report.result.p,4)],['صياغة أكاديمية',report.academicStatement],[],['المجموعة','العدد','المتوسط','الوسيط','الانحراف المعياري','أقل قيمة','أعلى قيمة'],...report.stats.map(x=>[x.label,x.n,fmt(x.mean),fmt(x.median),fmt(x.sd),fmt(x.min),fmt(x.max)])];download('statistical-analysis-report.csv','\ufeff'+csvRows(rows),'text/csv;charset=utf-8')};
document.querySelectorAll('input[name=design]').forEach(i=>i.onchange=()=>build());[variableType,goal].forEach(i=>i.onchange=()=>build());[analysisMode,manualMethod].forEach(i=>i.onchange=showAdvice);document.querySelectorAll('input[name=inputMethod]').forEach(i=>i.onchange=()=>{const m=new FormData(form).get('inputMethod');manualInput.classList.toggle('hidden',m!=='manual');fileInput.classList.toggle('hidden',m!=='file')});
form.onsubmit=async(e)=>{e.preventDefault();const o=opts(),m=new FormData(form).get('inputMethod');if(m==='file'){if(!dataFile.files[0]){results.innerHTML='<div class="alert">يرجى اختيار ملف بيانات أولًا.</div>';return}render(o,parseCsv(await dataFile.files[0].text()));return}render(o,data())};
enable(false);build();showAdvice();
